POST http://localhost:3003/api/blogs 
Content-type: application/json

{
    "title": "everything ok",
    "author": "Johanna L",
    "url": "http://google.fi",
    "likes": 32,
    "userId": "5f6b1ebbb8caa42e24f96069"
}